# Generated by Django 2.1.4 on 2020-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('project_name', models.CharField(max_length=64)),
                ('iteration_name', models.CharField(max_length=64)),
                ('mainfun', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
