# Generated by Django 2.1.4 on 2020-08-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='Case',
        ),
    ]
