# Generated by Django 2.1.4 on 2020-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_auto_20200811_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
