# Generated by Django 2.1.4 on 2020-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=18)),
                ('money', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已取消未退款'), (3, '已取消已退款')], default=0)),
                ('createUserName', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_time', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
            ],
        ),
    ]
