# Generated by Django 3.0.4 on 2020-08-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=20, unique=True, verbose_name='产品线名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_app',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=20)),
                ('system_name', models.CharField(max_length=20)),
                ('device_model', models.CharField(max_length=20)),
                ('system_version', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, verbose_name='只记录测试组名下的设备')),
                ('purchase_date', models.DateTimeField(verbose_name='购买时间')),
                ('location', models.IntegerField(choices=[(0, '深圳'), (1, '上海'), (2, '其他')], default=0)),
                ('remark', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_devices',
            },
        ),
        migrations.CreateModel(
            name='Iterable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=20, verbose_name='所属产品线')),
                ('publish_num', models.IntegerField(default=0, verbose_name='发版个数')),
                ('cases_num', models.IntegerField(default=0, verbose_name='用例条数')),
                ('bugs_num', models.IntegerField(default=0, verbose_name='用例条数')),
                ('test_user_id', models.CharField(max_length=20, verbose_name='测试人员ID')),
                ('op_user_name', models.CharField(default='', max_length=20, verbose_name='操作人')),
                ('start_time', models.DateTimeField(default='1970-01-01', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='1970-01-01', verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('year', models.IntegerField(default=2020, verbose_name='统计数据所属年')),
                ('month', models.IntegerField(default=1, verbose_name='统计数据所月份')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_iterable',
            },
        ),
        migrations.CreateModel(
            name='OnlineBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('back_bugs', models.IntegerField(default=0, verbose_name='反馈问题数')),
                ('online_bugs', models.IntegerField(default=0, verbose_name='线上问题数')),
                ('online_accidents', models.IntegerField(default=0, verbose_name='线上事故数')),
                ('test_user_id', models.CharField(default='', max_length=20, verbose_name='测试人员ID')),
                ('op_user_name', models.CharField(default='', max_length=20, verbose_name='操作人')),
                ('start_time', models.DateTimeField(default='1970-01-01', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='1970-01-01', verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('year', models.IntegerField(default=2020, verbose_name='统计数据所属年')),
                ('month', models.IntegerField(default=1, verbose_name='统计数据所月份')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_online_bug',
            },
        ),
        migrations.CreateModel(
            name='ProblemPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('avoid', models.CharField(max_length=100)),
                ('create_user', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=50)),
                ('case_info_url', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
            ],
            options={
                'db_table': 'qa_problem_plus',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20, verbose_name='项目组名称')),
                ('product_id', models.CharField(max_length=20, verbose_name='所属产品线')),
                ('test_user_id', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_project',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.IntegerField(choices=[(1, 'Gradle'), (2, 'Maven'), (3, 'Node'), (4, 'Python'), (5, 'Go'), (0, 'Others')], default=0, verbose_name='项目类型')),
                ('product_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('coder', models.CharField(max_length=30)),
                ('test_user_id', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_services',
            },
        ),
        migrations.CreateModel(
            name='SonarReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('service_num', models.IntegerField(default=0)),
                ('sonar_bugs', models.IntegerField(default=0)),
                ('sonar_holes', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=1)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=1970)),
                ('day', models.IntegerField(default=1)),
                ('is_month', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='月度数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'qa_sonar_result',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('iterable_name', models.CharField(max_length=50)),
                ('main_tasks', models.CharField(max_length=100)),
                ('test_cases_url', models.URLField()),
                ('test_user', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_test_cases',
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('iterable_name', models.CharField(max_length=50)),
                ('mainTasks', models.CharField(max_length=100)),
                ('test_report_url', models.URLField()),
                ('test_user', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_test_report',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_user',
            },
        ),
    ]
