# Generated by Django 2.1.4 on 2020-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterable',
            name='year',
            field=models.IntegerField(default=1970),
        ),
        migrations.AlterField(
            model_name='sonarreport',
            name='year',
            field=models.IntegerField(default=1970),
        ),
    ]
