# Generated by Django 2.1.4 on 2020-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterable',
            name='count_time',
        ),
        migrations.RemoveField(
            model_name='iterable',
            name='month_end',
        ),
        migrations.RemoveField(
            model_name='iterable',
            name='month_start',
        ),
        migrations.RemoveField(
            model_name='iterable',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='iterable',
            name='week_start',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='count_time',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='month_end',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='month_start',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='week_start',
        ),
        migrations.RemoveField(
            model_name='problemplus',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='problemplus',
            name='project_id',
        ),
        migrations.AddField(
            model_name='iterable',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='iterable',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
