# Generated by Django 2.1.4 on 2020-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iterable',
            name='month_end',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='月截止时间'),
        ),
        migrations.AlterField(
            model_name='iterable',
            name='month_start',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='月起始时间'),
        ),
        migrations.AlterField(
            model_name='iterable',
            name='week_end',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='周截止时间'),
        ),
        migrations.AlterField(
            model_name='iterable',
            name='week_start',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='周起始时间'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='month_end',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='月截止时间'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='month_start',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='月起始时间'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='week_end',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='周截止时间'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='week_start',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='周起始时间'),
        ),
        migrations.AlterField(
            model_name='sonarreport',
            name='month_end',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='月截止时间'),
        ),
        migrations.AlterField(
            model_name='sonarreport',
            name='month_start',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='月起始时间'),
        ),
        migrations.AlterField(
            model_name='sonarreport',
            name='week_end',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='周截止时间'),
        ),
        migrations.AlterField(
            model_name='sonarreport',
            name='week_start',
            field=models.DateTimeField(default='2020-07-08', null=True, verbose_name='周起始时间'),
        ),
    ]
