# Generated by Django 2.1.4 on 2020-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0002_auto_20200818_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project_id',
        ),
    ]
