# Generated by Django 2.1.4 on 2020-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0003_auto_20200908_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='mainTasks',
            field=models.CharField(max_length=200),
        ),
    ]
