# Generated by Django 2.1.4 on 2020-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0004_auto_20200818_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iterable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
