# Generated by Django 2.1.4 on 2020-08-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0005_auto_20200818_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonarreport',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
