# Generated by Django 2.1.4 on 2020-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0006_sonarreport_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebug',
            name='year',
            field=models.IntegerField(default=1970),
        ),
    ]
