# Generated by Django 2.1.4 on 2020-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0007_onlinebug_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
    ]
