# Generated by Django 2.1.4 on 2020-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0008_auto_20200819_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='iterable_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='main_tasks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='iterable_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='mainTasks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
