# Generated by Django 2.1.4 on 2020-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0009_auto_20200821_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterable',
            name='month',
        ),
        migrations.RemoveField(
            model_name='iterable',
            name='week',
        ),
        migrations.RemoveField(
            model_name='iterable',
            name='year',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='month',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='week',
        ),
        migrations.RemoveField(
            model_name='onlinebug',
            name='year',
        ),
        migrations.AddField(
            model_name='iterable',
            name='end_time',
            field=models.DateTimeField(default='1970-01-01', verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='iterable',
            name='op_user_name',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='iterable',
            name='start_time',
            field=models.DateTimeField(default='1970-01-01', verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='end_time',
            field=models.DateTimeField(default='1970-01-01', verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='op_user_name',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='start_time',
            field=models.DateTimeField(default='1970-01-01', verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='test_user_id',
            field=models.CharField(default='', max_length=20, verbose_name='测试人员ID'),
        ),
        migrations.AlterField(
            model_name='iterable',
            name='test_user_id',
            field=models.CharField(max_length=20, verbose_name='测试人员ID'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='back_bugs',
            field=models.IntegerField(default=0, verbose_name='反馈问题数'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='online_accidents',
            field=models.IntegerField(default=0, verbose_name='线上事故数'),
        ),
        migrations.AlterField(
            model_name='onlinebug',
            name='online_bugs',
            field=models.IntegerField(default=0, verbose_name='线上问题数'),
        ),
    ]
