# Generated by Django 3.0.4 on 2020-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0010_auto_20200824_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='devices',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='iterable',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='problemplus',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='services',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='user',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='操作人'),
        ),
    ]
