# Generated by Django 2.1.4 on 2020-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0011_auto_20200826_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterable',
            name='operator',
        ),
        migrations.AddField(
            model_name='iterable',
            name='month',
            field=models.IntegerField(default=1, verbose_name='统计数据所月份'),
        ),
        migrations.AddField(
            model_name='iterable',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='统计数据所属年'),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='month',
            field=models.IntegerField(default=1, verbose_name='统计数据所月份'),
        ),
        migrations.AddField(
            model_name='onlinebug',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='统计数据所属年'),
        ),
    ]
