# Generated by Django 3.0.4 on 2020-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0011_auto_20200826_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonarreport',
            name='is_month',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='月度数据'),
        ),
    ]
