# Generated by Django 3.0.4 on 2020-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0012_sonarreport_is_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_cases_url',
            field=models.URLField(),
        ),
    ]
