# Generated by Django 3.0.4 on 2020-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0013_auto_20200827_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
    ]
