# Generated by Django 3.0.4 on 2020-08-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0014_auto_20200827_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='iterable',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='problemplus',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='operator',
            field=models.CharField(max_length=20, verbose_name='操作人'),
        ),
    ]
