# Generated by Django 2.1.4 on 2020-09-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuglyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=50, verbose_name='事件')),
                ('timestamp', models.CharField(max_length=50, verbose_name='发布该数据时间搓')),
                ('date', models.CharField(max_length=10, verbose_name='数据收集日期')),
                ('appName', models.CharField(max_length=20, verbose_name='APP名称')),
                ('appId', models.CharField(max_length=20, verbose_name='AppID')),
                ('appUrl', models.URLField(verbose_name='数据查询链接')),
                ('version', models.CharField(max_length=50, verbose_name='APP版本')),
                ('platformId', models.IntegerField(default=1, verbose_name='APP平台')),
                ('signature', models.CharField(max_length=50)),
                ('accessCount', models.IntegerField(verbose_name='联网总次数')),
                ('accessUser', models.IntegerField(verbose_name='联网总人数')),
                ('crashCount', models.IntegerField(verbose_name='奔溃总次数')),
                ('crashUser', models.IntegerField(verbose_name='奔溃总人数')),
                ('url', models.URLField(verbose_name='该条数据查询链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='删除状态')),
            ],
            options={
                'db_table': 'qa_bugly',
            },
        ),
    ]
