# Generated by Django 2.1.4 on 2020-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=20, unique=True)),
                ('projectId', models.CharField(max_length=8, unique=True)),
                ('robotToken', models.URLField(max_length=120)),
                ('userName', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_time', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
            ],
            options={
                'db_table': 't_token',
            },
        ),
    ]
