# Generated by Django 2.1.4 on 2020-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttoken',
            name='projectName',
            field=models.CharField(max_length=20),
        ),
    ]
