# Generated by Django 3.0.4 on 2020-08-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapd', '0003_projecttoken_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttoken',
            name='is_delete',
        ),
    ]
